"""snapshot da norma e falha de IA na recomendacao

Revision ID: 345778d6e8f4
Revises: f8babbfb7a5b
Create Date: 2026-07-31 16:25:32.893836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '345778d6e8f4'
down_revision: Union[str, None] = 'f8babbfb7a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amostra_foliar', sa.Column('norma_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('recomendacao', sa.Column('falha_ia', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recomendacao', 'falha_ia')
    op.drop_column('amostra_foliar', 'norma_snapshot')
    # ### end Alembic commands ###
