"""tabelas iniciais do MER

Revision ID: f8babbfb7a5b
Revises: 
Create Date: 2026-07-30 17:50:37.535704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f8babbfb7a5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insumo',
    sa.Column('nome_comercial', sa.String(length=255), nullable=False),
    sa.Column('fabricante', sa.String(length=255), nullable=False),
    sa.Column('culturas_autorizadas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('concentracao_nutricional', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('norma_dris',
    sa.Column('cultura', sa.String(length=120), nullable=False),
    sa.Column('estadio_fenologico', sa.String(length=120), nullable=False),
    sa.Column('matriz_relacoes_duais', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('perfil', sa.Enum('ADMIN', 'AGRONOMO', name='perfil_usuario'), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('registro_crea', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_table('produtor',
    sa.Column('agronomo_id', sa.UUID(), nullable=False),
    sa.Column('nome_razao', sa.String(length=255), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agronomo_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agronomo_id', 'cpf_cnpj', name='uq_produtor_agronomo_doc')
    )
    op.create_index(op.f('ix_produtor_agronomo_id'), 'produtor', ['agronomo_id'], unique=False)
    op.create_table('propriedade',
    sa.Column('produtor_id', sa.UUID(), nullable=False),
    sa.Column('nome_fazenda', sa.String(length=255), nullable=False),
    sa.Column('municipio_uf', sa.String(length=120), nullable=False),
    sa.Column('area_total_ha', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produtor_id'], ['produtor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propriedade_produtor_id'), 'propriedade', ['produtor_id'], unique=False)
    op.create_table('talhao',
    sa.Column('propriedade_id', sa.UUID(), nullable=False),
    sa.Column('identificacao', sa.String(length=120), nullable=False),
    sa.Column('tamanho_ha', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('historico_culturas', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['propriedade_id'], ['propriedade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talhao_propriedade_id'), 'talhao', ['propriedade_id'], unique=False)
    op.create_table('amostra_foliar',
    sa.Column('talhao_id', sa.UUID(), nullable=False),
    sa.Column('norma_dris_id', sa.UUID(), nullable=False),
    sa.Column('data_coleta', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'AGUARDANDO_REVISAO', 'CONCLUIDA', name='status_amostra'), nullable=False),
    sa.Column('valor_ibn', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['norma_dris_id'], ['norma_dris.id'], ),
    sa.ForeignKeyConstraint(['talhao_id'], ['talhao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amostra_foliar_talhao_id'), 'amostra_foliar', ['talhao_id'], unique=False)
    op.create_table('indice_nutricional',
    sa.Column('amostra_foliar_id', sa.UUID(), nullable=False),
    sa.Column('elemento', sa.String(length=5), nullable=False),
    sa.Column('valor_laboratorio', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('indice_dris_calculado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('classificacao', sa.Enum('DEFICIENTE', 'EQUILIBRIO', 'EXCESSO', name='classificacao_nutriente'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['amostra_foliar_id'], ['amostra_foliar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amostra_foliar_id', 'elemento', name='uq_indice_amostra_elemento')
    )
    op.create_index(op.f('ix_indice_nutricional_amostra_foliar_id'), 'indice_nutricional', ['amostra_foliar_id'], unique=False)
    op.create_table('recomendacao',
    sa.Column('amostra_foliar_id', sa.UUID(), nullable=False),
    sa.Column('texto_rascunho_ia', sa.Text(), nullable=True),
    sa.Column('texto_final_editado', sa.Text(), nullable=True),
    sa.Column('data_emissao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['amostra_foliar_id'], ['amostra_foliar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amostra_foliar_id')
    )
    op.create_table('recomendacao_insumo',
    sa.Column('recomendacao_id', sa.UUID(), nullable=False),
    sa.Column('insumo_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumo.id'], ),
    sa.ForeignKeyConstraint(['recomendacao_id'], ['recomendacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recomendacao_insumo_recomendacao_id'), 'recomendacao_insumo', ['recomendacao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recomendacao_insumo_recomendacao_id'), table_name='recomendacao_insumo')
    op.drop_table('recomendacao_insumo')
    op.drop_table('recomendacao')
    op.drop_index(op.f('ix_indice_nutricional_amostra_foliar_id'), table_name='indice_nutricional')
    op.drop_table('indice_nutricional')
    op.drop_index(op.f('ix_amostra_foliar_talhao_id'), table_name='amostra_foliar')
    op.drop_table('amostra_foliar')
    op.drop_index(op.f('ix_talhao_propriedade_id'), table_name='talhao')
    op.drop_table('talhao')
    op.drop_index(op.f('ix_propriedade_produtor_id'), table_name='propriedade')
    op.drop_table('propriedade')
    op.drop_index(op.f('ix_produtor_agronomo_id'), table_name='produtor')
    op.drop_table('produtor')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('norma_dris')
    op.drop_table('insumo')
    # ### end Alembic commands ###
